-- Member
    INSERT INTO MEMBER (mID, mPW, mNAME, mBIRTH, mEMAIL, mMOTTO, mSTATUS) 
        VALUES ('aaa', '111', '홍길동', TO_DATE('2000-01-01', 'YYYY-MM-DD'), 'park@park.com', NULL, 1);
    INSERT INTO MEMBER (mID, mPW, mNAME, mBIRTH, mEMAIL, mMOTTO, mSTATUS) 
        VALUES ('bbb', '111', '김아무개', TO_DATE('2000-01-01', 'YYYY-MM-DD'), 'bb@bb.com', NULL, 1);
    INSERT INTO MEMBER (mID, mPW, mNAME, mBIRTH, mEMAIL, mMOTTO, mSTATUS) 
        VALUES ('ccc', '111', '이학도', TO_DATE('2000-01-01', 'YYYY-MM-DD'), 'ccc@ccc.com', NULL, 1);
    INSERT INTO MEMBER (mID, mPW, mNAME, mBIRTH, mEMAIL, mMOTTO, mSTATUS) 
        VALUES ('ddd', '111', '성춘향', TO_DATE('2000-01-01', 'YYYY-MM-DD'), 'ddd@ddd.com', NULL, 1);
    INSERT INTO MEMBER (mID, mPW, mNAME, mBIRTH, mEMAIL, mMOTTO, mSTATUS) 
        VALUES ('eee', '111', '박철수', TO_DATE('2000-01-01', 'YYYY-MM-DD'), 'eee@eee.com', NULL, 1);
    SELECT * FROM MEMBER;
    COMMIT;
-- Admin
   INSERT INTO ADMIN (aID, aPW, aGRADE) 
        VALUES ('aa', '111', 1);
-- TEAM
   INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'aaa', 'MYLOG', '아자아자'); 
    INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'bbb', 'BEEBEE', 'NOpainNOgain');
    INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'ccc', 'SOLACCI', 'solacci');
    INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'ddd', 'DD', 'DDistheBest');
    INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'eee', 'leelee', 'leeee');
    INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'ddd', 'DIY', 'noGoal');
    INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'ccc', 'CICI', NULL);
    INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'bbb', 'BECOME', NULL);
   INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'aaa', 'AYY~!', NULL);
   INSERT INTO TEAM (tNO, mID, tNAME, tGOAL) 
        VALUES (TEAM_SEQ.NEXTVAL, 'eee', 'EE', NULL); 
    SELECT * FROM TEAM;
-- TEAM_MEMBER
   INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'aaa', 1, 1);
    INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'bbb', 2, 1);
    INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'ccc', 3, 1);
    INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'ddd', 4, 1);
    INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'eee', 5, 1);
    INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'ddd', 6, 1);
    INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'ccc', 7, 1);
    INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'bbb', 8, 1);
    INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'aaa', 9, 1);
    INSERT INTO TEAM_MEMBER (tmNO, mID, tNO, tmCHECK) 
        VALUES (TEAM_MEMBER_SEQ.NEXTVAL, 'eee', 10, 1);
    SELECT * FROM TEAM_MEMBER; 
-- TEAMBOARD
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'aaa', '같이 노력하실 분 구합니다', '테스트�', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'ccc', '팀원찾아요', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'bbb', '팀원 모집합니다', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'eee', '함께 목표를 이룰 분~', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'ddd', '팀원모집', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'bbb', '같이해요', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'aaa', '우리는 모두 할 수 있어요', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'ccc', '아자아자 열심히 하실 분!', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'ddd', '함께 하실래요?', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'eee', '같이 다이어트해요!', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'ddd', '같이 공부하실 분 구해요', '테스트', 0, SYSDATE, NULL);
    INSERT INTO TEAMBOARD (tNUM, mID, tTITLE, tCONTENT, tHIT, tRDATE, tIP) 
        VALUES (TEAMBOARD_SEQ.NEXTVAL, 'bbb', '팀 모집합니다 예~!~!', '테스트', 0, SYSDATE, NULL);
    SELECT * FROM TEAMBOARD;
    commit;
--TEAM_TODO
    INSERT INTO TEAM_TODO (ttNO, tNO, ttCONTENT, ttCHECK, tmNO, ttORDER, ttRDATE) 
        VALUES (TEAM_TODO_SEQ.NEXTVAL, 1, 'ppt 템플릿 정하기', 0, 1, TEAM_TODO_SEQ.CURRVAL , '2022-08-18');
    INSERT INTO TEAM_TODO (ttNO, tNO, ttCONTENT, ttCHECK, tmNO, ttORDER, ttRDATE) 
        VALUES (TEAM_TODO_SEQ.NEXTVAL, 2, 'ppt 만들기', 0, 1, TEAM_TODO_SEQ.CURRVAL , '2022-08-18');
    INSERT INTO TEAM_TODO (ttNO, tNO, ttCONTENT, ttCHECK, tmNO, ttORDER, ttRDATE) 
        VALUES (TEAM_TODO_SEQ.NEXTVAL, 3, '발표 대본 작성하기', 0, 1, TEAM_TODO_SEQ.CURRVAL , '2022-08-18');
    INSERT INTO TEAM_TODO (ttNO, tNO, ttCONTENT, ttCHECK, tmNO, ttORDER, ttRDATE) 
        VALUES (TEAM_TODO_SEQ.NEXTVAL, 4, '주제 선정하기', 0, 1, TEAM_TODO_SEQ.CURRVAL , '2022-08-18');
    INSERT INTO TEAM_TODO (ttNO, tNO, ttCONTENT, ttCHECK, tmNO, ttORDER, ttRDATE) 
        VALUES (TEAM_TODO_SEQ.NEXTVAL, 5, '발표자 정하기', 0, 1, TEAM_TODO_SEQ.CURRVAL , '2022-08-18');
    SELECT * FROM TEAM_TODO;    
        
        
        