DROP TABLE QNA_BOARD;
DROP TABLE FRIEND;
DROP TABLE NOTICE_BOARD;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP SEQUENCE FRIEND_SEQ;
DROP SEQUENCE QNA_SEQ;
DROP SEQUENCE NOTICE_SEQ;

CREATE TABLE MEMBER(
    MID VARCHAR2(15) PRIMARY KEY,
    MPW VARCHAR2(15),
    MNAME VARCHAR2(30),
    MBIRTH DATE,
    MEMAIL VARCHAR2(50) UNIQUE,
    MMOTTO VARCHAR2(500),
    MSTATUS NUMBER(1) DEFAULT 1
);

INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO, MSTATUS) VALUES ('aaa', '111', '닉네임', '2000-01-01', 'aaa@a.com', '나는 최고다', '1');
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO, MSTATUS) VALUES ('bbb', '111', '닉네임', '2000-01-01', 'bbb@b.com', '나는 최고다', '1');
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO) VALUES ('ddd', '111', '닉네임', '2000-01-01', 'ddd@d.com', '나는 최고다');

SELECT * FROM MEMBER;

select count(*) from member where memail = 'leekr44@naver.com';

SELECT COUNT(*) FROM MEMBER WHERE MID = 'aaa';
SELECT * FROM MEMBER WHERE MEMAIL LIKE 'aaa'||'%';

CREATE TABLE FRIEND(
    FNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    FID VARCHAR2(15) REFERENCES MEMBER(MID)
);

CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'bbb');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'ccc');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'bbb', 'ccc');

SELECT * FROM FRIEND WHERE MID = 'aaa';


CREATE TABLE ADMIN(
    AID VARCHAR2(15) PRIMARY KEY,
    APW VARCHAR2(15),
    AGRADE NUMBER(1) DEFAULT 0
);

INSERT INTO ADMIN (AID, APW) VALUES ('admin', '111');

SELECT * FROM ADMIN;

CREATE TABLE QNA_BOARD(
    QNO NUMBER(8) PRIMARY KEY,
    QTITLE VARCHAR2(100),
    QCONTENT VARCHAR2(4000),
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    QDATE DATE DEFAULT SYSDATE,
    QHIT NUMBER(8) DEFAULT 0,
    QGROUP NUMBER(8),
    QSTEP NUMBER(4) DEFAULT 0,
    QINDENT NUMBER(4) DEFAULT 0,
    QIP VARCHAR2(20)
);

CREATE SEQUENCE QNA_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

-- 질문
INSERT INTO QNA_BOARD (QNO, QTITLE, QCONTENT, MID, QGROUP, QIP)
    VALUES (QNA_SEQ.NEXTVAL, '질문있습니다', '질문드립니다', 'aaa', QNA_SEQ.CURRVAL, '127.0.0.1');

-- 답변
INSERT INTO QNA_BOARD (QNO, QTITLE, QCONTENT, AID, QGROUP, QSTEP, QINDENT, QIP)
    VALUES (QNA_SEQ.NEXTVAL, '답변', '답변이다', 'admin', 1, 1, 1, '127.0.0.1');
    
SELECT * FROM QNA_BOARD;

CREATE TABLE NOTICE_BOARD(
    NNO NUMBER(8) PRIMARY KEY,
    NTITLE VARCHAR2(100),
    NCONTENT VARCHAR2(4000),
    NRDATE DATE DEFAULT SYSDATE,
    NHIT NUMBER(8) DEFAULT 0,
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    NIP VARCHAR2(20)
);

CREATE SEQUENCE NOTICE_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
    
INSERT INTO NOTICE_BOARD (NNO, NTITLE, NCONTENT, AID, NIP)
    VALUES (NOTICE_SEQ.NEXTVAL, '공지', '내용', 'admin', '127.0.0.1');
    
SELECT * FROM NOTICE_BOARD;



INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO)
				VALUES ('ggg', '111', '닉네임', '2022-08-01', 'ggg@g.com', '나는 최고다');

			INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL, MMOTTO)
				VALUES ('hhh', '111', '닉네임', 'hhh@h.com', '나는 최고다');
                
			INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL)
				VALUES ('iii', '111', '닉네임', '2022-08-01', 'iii@i.com');
                
			INSERT INTO MEMBER (MID, MPW, MNAME, MEMAIL)
				VALUES ('jjj', '111', '닉네임', 'jjj@j.com');

SELECT * FROM MEMBER WHERE MNAME= '닉네임' AND MEMAIL = 'aaa@a.com';

DROP TABLE QNABOARD;
DROP TABLE NOTICEBOARD;
DROP SEQUENCE QNABOARD_SEQ;
DROP SEQUENCE NOTICEBOARD_SEQ;

CREATE TABLE NOTICEBOARD(
    NNO NUMBER(8) PRIMARY KEY,
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    NTITLE VARCHAR2(100) NOT NULL,
    NCONTENT VARCHAR2(3000) NOT NULL,
    NRDATE DATE DEFAULT SYSDATE,
    NHIT NUMBER(8) DEFAULT 0,
    NIP VARCHAR2(20)
);

CREATE SEQUENCE NOTICEBOARD_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

INSERT INTO NOTICEBOARD (NNO, AID, NTITLE, NCONTENT, NIP)
    VALUES (NOTICEBOARD_SEQ.NEXTVAL, 'admin', '공지', '공지합니다', '127.0.0.1');
    
SELECT *
    FROM (SELECT ROWNUM RN, A.*
            FROM (SELECT * FROM NOTICEBOARD ORDER BY NNO DESC) A)
    WHERE RN BETWEEN 1 AND 10;

UPDATE NOTICEBOARD SET NTITLE = '수정공지', NCONTENT = '수정공지합니다', NIP = '127.0.0.2'
    WHERE NNO = 1;
    
DELETE FROM NOTICEBOARD WHERE NNO = 2;

UPDATE NOTICEBOARD SET NHIT = NHIT + 1 WHERE NNO = 1;

SELECT COUNT(*) FROM NOTICEBOARD;

SELECT * FROM NOTICEBOARD WHERE NNO = 1;

CREATE TABLE QNABOARD(
    QNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    QWRITER VARCHAR2(30) NOT NULL,
    QTITLE VARCHAR2(100) NOT NULL,
    QCONTENT VARCHAR2(3000) NOT NULL,
    QRDATE DATE DEFAULT SYSDATE,
    QHIT NUMBER(8) DEFAULT 0,
    QGROUP NUMBER(8),
    QSTEP NUMBER(4),
    QINDENT NUMBER(4),
    QIP VARCHAR2(20)
);

CREATE SEQUENCE QNABOARD_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
    
INSERT INTO QNABOARD (QNO, MID, QWRITER, QTITLE, QCONTENT, QGROUP, QSTEP, QINDENT, QIP)
    VALUES (QNABOARD_SEQ.NEXTVAL, 'qqq', '최강','문의드립니다', '답변주세요', QNABOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');

UPDATE QNABOARD SET QTITLE = '수정문의드립니다', QCONTENT = '수정답변주세요' WHERE QNO = 1;

DELETE FROM QNABOARD WHERE QNO = 2;

SELECT * FROM QNABOARD WHERE QNO = 1;

UPDATE QNABOARD SET QHIT = QHIT + 1 WHERE QNO = 1;

SELECT *
    FROM (SELECT ROWNUM RN, A.*
            FROM (SELECT * FROM QNABOARD
                     ORDER BY QGROUP DESC, QSTEP) A)
    WHERE RN BETWEEN 1 AND 10;
    
SELECT *
    FROM (SELECT ROWNUM RN, A.*
            FROM (SELECT * FROM QNABOARD
                     ORDER BY QGROUP DESC, QSTEP) A)
    WHERE MID = 'qqq' AND RN BETWEEN 1 AND 10;

UPDATE QNABOARD SET QSTEP = QSTEP + 1 WHERE QGROUP = 1 AND QSTEP > 0;

INSERT INTO QNABOARD (QNO, MID, AID, QWRITER,QTITLE, QCONTENT, QGROUP, QSTEP, QINDENT, QIP)
    VALUES (QNABOARD_SEQ.NEXTVAL, 'qqq', 'admin', '관리자', '답변드립니다', '이해하셨죠?', 1, 1, 1, '127.0.0.1');

SELECT COUNT(*) FROM QNABOARD;

SELECT COUNT(*) FROM QNABOARD WHERE MID = 'qqq';

COMMIT;







