DROP TABLE QNA_BOARD;
DROP TABLE FRIEND;
DROP TABLE NOTICE_BOARD;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP SEQUENCE FRIEND_SEQ;
DROP SEQUENCE QNA_SEQ;
DROP SEQUENCE NOTICE_SEQ;

CREATE TABLE MEMBER(
    MID VARCHAR2(15) PRIMARY KEY,
    MPW VARCHAR2(15),
    MNAME VARCHAR2(30),
    MBIRTH DATE,
    MEMAIL VARCHAR2(30) UNIQUE,
    MMOTTO VARCHAR2(100),
    MDATE DATE DEFAULT SYSDATE,
    MSTATUS CHAR(1)
);

INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO, MSTATUS) VALUES ('aaa', '111', '닉네임', '2000-01-01', 'aaa@a.com', '나는 최고다', '1');
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO, MSTATUS) VALUES ('bbb', '111', '닉네임', '2000-01-01', 'bbb@b.com', '나는 최고다', '1');
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO, MSTATUS) VALUES ('ccc', '111', '닉네임', '2000-01-01', 'ccc@c.com', '나는 최고다', '1');

SELECT * FROM MEMBER;

CREATE TABLE FRIEND(
    FNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    FID VARCHAR2(15) REFERENCES MEMBER(MID)
);

CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'bbb');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'ccc');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'bbb', 'ccc');

SELECT * FROM FRIEND WHERE MID = 'aaa';


CREATE TABLE ADMIN(
    AID VARCHAR2(15) PRIMARY KEY,
    APW VARCHAR2(15),
    ADATE DATE DEFAULT SYSDATE
);

INSERT INTO ADMIN (AID, APW) VALUES ('admin', '111');

SELECT * FROM ADMIN;

CREATE TABLE QNA_BOARD(
    QNO NUMBER(8) PRIMARY KEY,
    QTITLE VARCHAR2(100),
    QCONTENT VARCHAR2(4000),
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    QDATE DATE DEFAULT SYSDATE,
    QHIT NUMBER(8) DEFAULT 0,
    QGROUP NUMBER(8),
    QSTEP NUMBER(4) DEFAULT 0,
    QINDENT NUMBER(4) DEFAULT 0,
    QIP VARCHAR2(20)
);

CREATE SEQUENCE QNA_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

-- 질문
INSERT INTO QNA_BOARD (QNO, QTITLE, QCONTENT, MID, QGROUP, QIP)
    VALUES (QNA_SEQ.NEXTVAL, '질문있습니다', '질문드립니다', 'aaa', QNA_SEQ.CURRVAL, '127.0.0.1');

-- 답변
INSERT INTO QNA_BOARD (QNO, QTITLE, QCONTENT, AID, QGROUP, QSTEP, QINDENT, QIP)
    VALUES (QNA_SEQ.NEXTVAL, '답변', '답변이다', 'admin', 1, 1, 1, '127.0.0.1');
    
SELECT * FROM QNA_BOARD;

CREATE TABLE NOTICE_BOARD(
    NNO NUMBER(8) PRIMARY KEY,
    NTITLE VARCHAR2(100),
    NCONTENT VARCHAR2(4000),
    NDATE DATE DEFAULT SYSDATE,
    NHIT NUMBER(8) DEFAULT 0,
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    NIP VARCHAR2(20)
);

CREATE SEQUENCE NOTICE_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
    
INSERT INTO NOTICE_BOARD (NNO, NTITLE, NCONTENT, AID, NIP)
    VALUES (NOTICE_SEQ.NEXTVAL, '공지', '내용', 'admin', '127.0.0.1');
    
SELECT * FROM NOTICE_BOARD;












