DROP SEQUENCE TODO_SEQ;
DROP SEQUENCE DIARYBOARD_SEQ;
DROP SEQUENCE DIARYREPLY_SEQ;
DROP SEQUENCE FRIEND_SEQ;
DROP SEQUENCE ACCOUNTBOOK_SEQ;
DROP SEQUENCE ACCOUNTCATEGORY_SEQ;
DROP SEQUENCE TEAM_COMMENTBOARD_SEQ;
DROP SEQUENCE TEAM_SEQ;
DROP SEQUENCE TEAM_MEMBER_SEQ;
DROP SEQUENCE TEAM_TODO_SEQ;
DROP SEQUENCE TEAMBOARD_SEQ;
DROP SEQUENCE QNABOARD_SEQ;
DROP SEQUENCE NOTICEBOARD_SEQ;
DROP SEQUENCE ALERT_SEQ;
DROP SEQUENCE ALERT_CODE_SEQ;
DROP SEQUENCE RSEQ;
DROP SEQUENCE RPSEQ;
DROP SEQUENCE HSEQ;
DROP SEQUENCE BTSEQ;
DROP SEQUENCE TBSEQ;
DROP SEQUENCE TSEQ;


CREATE SEQUENCE ACCOUNTBOOK_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ACCOUNTCATEGORY_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE FRIEND_SEQ MAXVALUE 9999999 NOCACHE NOCYCLE;
CREATE SEQUENCE TODO_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE DIARYBOARD_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE DIARYREPLY_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM_COMMENTBOARD_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM_MEMBER_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAM_TODO_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE TEAMBOARD_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE NOTICEBOARD_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE QNABOARD_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ALERT_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ALERT_CODE_SEQ MAXVALUE 99999999 NOCACHE NOCYCLE;
CREATE SEQUENCE RSEQ MAXVALUE 99999999 NOCYCLE NOCACHE;
CREATE SEQUENCE RPSEQ MAXVALUE 99999999 NOCYCLE NOCACHE;
CREATE SEQUENCE HSEQ MAXVALUE 99999999 NOCYCLE NOCACHE;
CREATE SEQUENCE BTSEQ MAXVALUE 99999999 NOCYCLE NOCACHE;
CREATE SEQUENCE TBSEQ MAXVALUE 99999999 NOCYCLE NOCACHE;
CREATE SEQUENCE TSEQ MAXVALUE 99999999 NOCYCLE NOCACHE;


DROP TABLE FRIEND;
DROP TABLE DIARYREPLY;
DROP TABLE DIARYBOARD;
DROP TABLE TODO;
DROP TABLE ACCOUNTBOOK;
DROP TABLE ACCOUNTCATEGORY;
DROP TABLE TEAM_COMMENTBOARD;
DROP TABLE TEAM_TODO;
DROP TABLE TEAM_MEMBER;
DROP TABLE TEAM;
DROP TABLE TEAMBOARD;
DROP TABLE QNABOARD;
DROP TABLE NOTICEBOARD;
DROP TABLE ALERT;
DROP TABLE ALERT_CODE;
DROP TABLE BOARD_TAG;
DROP TABLE RPBOARD;
DROP TABLE RBOARD;
DROP TABLE HASHTAG;
DROP TABLE TTABLE;
DROP TABLE TIMER;
DROP TABLE ADMIN;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
       mID VARCHAR2(15) PRIMARY KEY,
       mPW VARCHAR2(15) NOT NULL,
       mNAME VARCHAR2(30) NOT NULL,
       mBIRTH DATE,
       mEMAIL VARCHAR2(30) UNIQUE NOT NULL,
       mMOTTO VARCHAR2(100),
       mSTATUS NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE ADMIN (
    AID VARCHAR2(15) PRIMARY KEY,
    APW VARCHAR2(15),
    AGRADE NUMBER(1)
);

CREATE TABLE FRIEND(
    FNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    FID VARCHAR2(15) REFERENCES MEMBER(MID)
);

CREATE TABLE TIMER(
    TNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    TTODAY DATE DEFAULT SYSDATE,
    TNAME VARCHAR2(100),
    TDO NUMBER(2) DEFAULT 0,
    TPAUSE NUMBER(8) DEFAULT 0,
    TDURING NUMBER(8) DEFAULT 0,
    TSTART NUMBER(8) DEFAULT 0,
    TEND NUMBER(8) DEFAULT 0
    
);

CREATE TABLE TTABLE(
    TBNO NUMBER(8)PRIMARY KEY,
    TNO NUMBER(8)REFERENCES TIMER(TNO) ,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    TBSHOUR NUMBER(8)DEFAULT 0, 
    TBSMIN NUMBER(8)DEFAULT 0,
    TBEHOUR NUMBER(8)DEFAULT 0,
    TBEMIN NUMBER(8)DEFAULT 0
    
);

CREATE TABLE HASHTAG(
    HNO NUMBER(8) PRIMARY KEY,
    HNAME VARCHAR2(50) NOT NULL
);

CREATE TABLE RBOARD(
    RNUM NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(50) REFERENCES MEMBER(MID),
    RTITLE VARCHAR2(100) NOT NULL,
    RCONTENT CLOB NOT NULL,
    RFILENAME VARCHAR2(100),
    RRDATE DATE DEFAULT SYSDATE,
    RHIT NUMBER(8),
    RSTATUS NUMBER(1) DEFAULT 0,
    RIP VARCHAR2(20)
);

CREATE TABLE RPBOARD(
    RPNUM NUMBER(8) PRIMARY KEY,
    RNUM NUMBER(8) REFERENCES RBOARD(RNUM),
    MID VARCHAR2(50) REFERENCES MEMBER(MID),
    RPCONTENT VARCHAR2(1000) NOT NULL,
    RPDATE DATE DEFAULT SYSDATE,
    RPGROUP NUMBER(8) NOT NULL,
    RPINDENT NUMBER(4),
    RPMENTION VARCHAR2(30),
    RPIP VARCHAR2(20)
);

CREATE TABLE BOARD_TAG(
    BTNO NUMBER(8) PRIMARY KEY,
    HNO NUMBER(8) REFERENCES HASHTAG(HNO),
    RNUM NUMBER(8) REFERENCES RBOARD(RNUM)
    on delete cascade
);

CREATE TABLE NOTICEBOARD(
    NNO NUMBER(8) PRIMARY KEY,
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    NTITLE VARCHAR2(100) NOT NULL,
    NCONTENT VARCHAR2(3000) NOT NULL,
    NRDATE DATE DEFAULT SYSDATE,
    NHIT NUMBER(8) DEFAULT 0,
    NIP VARCHAR2(20)
);

CREATE TABLE ALERT_CODE(
    ALCODE NUMBER(8) PRIMARY KEY,
    CODENAME VARCHAR2(30)
);

CREATE TABLE ALERT(
    ALNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    FID VARCHAR2(15) REFERENCES MEMBER(MID),
    ALCODE NUMBER(8) REFERENCES ALERT_CODE(ALCODE),
    ALCHECK NUMBER(1) DEFAULT 0,
    ALDATE DATE DEFAULT SYSDATE
);

CREATE TABLE QNABOARD(
    QNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    QWRITER VARCHAR2(30) NOT NULL,
    QTITLE VARCHAR2(100) NOT NULL,
    QCONTENT VARCHAR2(3000) NOT NULL,
    QRDATE DATE DEFAULT SYSDATE,
    QHIT NUMBER(8) DEFAULT 0,
    QGROUP NUMBER(8),
    QSTEP NUMBER(4),
    QINDENT NUMBER(4),
    QIP VARCHAR2(20)
);

CREATE TABLE TEAM(
        tNO NUMBER(8) PRIMARY KEY,
        mID VARCHAR2(15) REFERENCES  MEMBER(mID),
        tNAME VARCHAR2(100) NOT NULL,
        tGOAL VARCHAR2(100)
);

CREATE TABLE TEAM_MEMBER(
        tmNO NUMBER(8) PRIMARY KEY,
        mID VARCHAR2(15) REFERENCES MEMBER(mID) NOT NULL,
        tNO NUMBER(8) REFERENCES TEAM(tNO) NOT NULL,
        tmCHECK NUMBER(1) DEFAULT 0 NOT NULL
);

 CREATE TABLE TEAM_TODO(
        ttNO NUMBER(8) PRIMARY KEY,
        tNO NUMBER(8) REFERENCES TEAM(tNO),
        ttCONTENT VARCHAR2(4000) NOT NULL,
        ttCHECK NUMBER(2) DEFAULT 0 NOT NULL,
        tmNO NUMBER(8) REFERENCES TEAM_MEMBER(tmNO),
        ttORDER NUMBER(6),
        ttRDATE DATE DEFAULT SYSDATE
);
CREATE TABLE TEAMBOARD(
        tNUM NUMBER(8) PRIMARY KEY,
        mID VARCHAR2(15) REFERENCES MEMBER(mID),
        tTITLE VARCHAR2(100) NOT NULL,
        tCONTENT CLOB NOT NULL,
        tHIT NUMBER(8) DEFAULT 0,
        tRDATE DATE DEFAULT SYSDATE,
        tIP VARCHAR2(20)
);
CREATE TABLE TEAM_COMMENTBOARD(
        tcNUM NUMBER(8) PRIMARY KEY,
        mID VARCHAR2(15) REFERENCES MEMBER(mID),
        tcMENTION VARCHAR2(30),
        tNUM NUMBER(8) REFERENCES TEAMBOARD(tNUM),
        tcCONTENT VARCHAR2(1000) NOT NULL,
        tcRDATE DATE DEFAULT SYSDATE,
        tcGROUP NUMBER(8) DEFAULT 0,
        tcINDENT NUMBER(4) DEFAULT 0,
        tcIP VARCHAR2(20)
);

CREATE TABLE ACCOUNTCATEGORY(
    ACNO NUMBER(8) PRIMARY KEY,
    ATITLE VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE ACCOUNTBOOK(
    ANO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    ACNO NUMBER(8) NOT NULL,
    ACONTENT VARCHAR2(500) NOT NULL,
    APRICE NUMBER(9) NOT NULL,
    ADATE DATE NOT NULL,
    ASTATUS NUMBER(1) DEFAULT 0 NOT NULL 
);

CREATE TABLE TODO(
    TDNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    TDCONTENT VARCHAR(100) NOT NULL,
    TDCHECK NUMBER(1) DEFAULT 0 NOT NULL,
    TDRDATE DATE NOT NULL );

CREATE TABLE DIARYBOARD(
    DNUM NUMBER(8) PRIMARY KEY,
    DTITLE VARCHAR2(100) NOT NULL,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    DTODOIN NUMBER(1),
    DCONTENT CLOB NOT NULL,
    DHIT NUMBER(5) DEFAULT 0 NOT NULL,
    DSTATUS CHAR(2) NOT NULL,
    DDATE DATE NOT NULL,
    DRDATE DATE DEFAULT SYSDATE NOT NULL,
    DIP VARCHAR2(20) NOT NULL   );
    
CREATE TABLE DIARYREPLY(
    DRNUM NUMBER(8) PRIMARY KEY,
    DNUM NUMBER(8) REFERENCES DIARYBOARD(DNUM),
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    DRMENTION VARCHAR2(30),
    DRCONTENT VARCHAR2(1000) NOT NULL,
    DRGROUP NUMBER(9) NOT NULL,
    DRINDENT NUMBER(1) NOT NULL,
    DRRDATE DATE DEFAULT SYSDATE NOT NULL,
    DRIP VARCHAR2(20) NOT NULL  );