DROP TABLE QNABOARD  CASCADE CONSTRAINTS;
DROP TABLE FRIEND  CASCADE CONSTRAINTS;
DROP TABLE NOTICEBOARD  CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP SEQUENCE FRIEND_SEQ;
DROP SEQUENCE QNABOARD_SEQ;
DROP SEQUENCE NOTICEBOARD_SEQ;

-- 회원
CREATE TABLE MEMBER(
    MID VARCHAR2(15) PRIMARY KEY,
    MPW VARCHAR2(15),
    MNAME VARCHAR2(30),
    MBIRTH DATE,
    MEMAIL VARCHAR2(50) UNIQUE,
    MMOTTO VARCHAR2(500),
    MSTATUS NUMBER(1) DEFAULT 1
);

-- 관리자
CREATE TABLE ADMIN (
    AID VARCHAR2(15) PRIMARY KEY,
    APW VARCHAR2(15),
    AGRADE NUMBER(1)
);

-- 친구
CREATE TABLE FRIEND(
    FNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    FID VARCHAR2(15) REFERENCES MEMBER(MID)
);

CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
    
-- 공지사항
CREATE TABLE NOTICEBOARD(
    NNO NUMBER(8) PRIMARY KEY,
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    NTITLE VARCHAR2(100) NOT NULL,
    NCONTENT VARCHAR2(3000) NOT NULL,
    NRDATE DATE DEFAULT SYSDATE,
    NHIT NUMBER(8) DEFAULT 0,
    NIP VARCHAR2(20)
);

CREATE SEQUENCE NOTICEBOARD_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
    
-- QNA
CREATE TABLE QNABOARD(
    QNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    QWRITER VARCHAR2(30) NOT NULL,
    QTITLE VARCHAR2(100) NOT NULL,
    QCONTENT VARCHAR2(3000) NOT NULL,
    QRDATE DATE DEFAULT SYSDATE,
    QHIT NUMBER(8) DEFAULT 0,
    QGROUP NUMBER(8),
    QSTEP NUMBER(4),
    QINDENT NUMBER(4),
    QIP VARCHAR2(20)
);

CREATE SEQUENCE QNABOARD_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
    
    
DROP TABLE ALERT;
DROP TABLE ALERT_CODE;
DROP SEQUENCE ALERT_SEQ;
DROP SEQUENCE ALERT_CODE_SEQ;

-- 알림코드
CREATE TABLE ALERT_CODE(
    ALCODE NUMBER(8) PRIMARY KEY,
    CODENAME VARCHAR2(30)
);

-- 알림
CREATE TABLE ALERT(
    ALNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    FID VARCHAR2(15) REFERENCES MEMBER(MID),
    ALCODE NUMBER(8) REFERENCES ALERT_CODE(ALCODE),
    ALCHECK NUMBER(1) DEFAULT 0,
    ALDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE ALERT_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE ALERT_CODE_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;
