DROP TABLE QNABOARD;
DROP TABLE FRIEND;
DROP TABLE NOTICEBOARD;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP SEQUENCE FRIEND_SEQ;
DROP SEQUENCE QNA_SEQ;
DROP SEQUENCE NOTICE_SEQ;

-- 회원
CREATE TABLE MEMBER(
    MID VARCHAR2(15) PRIMARY KEY,
    MPW VARCHAR2(15),
    MNAME VARCHAR2(30),
    MBIRTH DATE,
    MEMAIL VARCHAR2(50) UNIQUE,
    MMOTTO VARCHAR2(500),
    MSTATUS NUMBER(1) DEFAULT 1
);

-- 회원 더미
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO, MSTATUS) VALUES ('aaa', '111', '닉네임', '2000-01-01', 'aaa@a.com', '나는 최고다', '1');
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO, MSTATUS) VALUES ('bbb', '111', '닉네임', '2000-01-01', 'bbb@b.com', '나는 최고다', '1');
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO) VALUES ('ccc', '111', '닉네임', '2000-01-01', 'ccc@c.com', '나는 최고다');
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL, MMOTTO) VALUES ('kkk', '111', '닉네임', '2000-01-01', 'kkk@k.com', '나는 최고다');
select * from member;
-- 이메일 중복체크
SELECT * FROM MEMBER WHERE MEMAIL = 'leekr44@naver.com';

-- 아이디 중복체크
SELECT COUNT(*) FROM MEMBER WHERE MID = 'aaa';

-- 친구
CREATE TABLE FRIEND(
    FNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    FID VARCHAR2(15) REFERENCES MEMBER(MID)
);

CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

commit;
-- 친구 더미
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'jjj');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'kkk');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'fff');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'ggg');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'hhh');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'iii');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'aaa', 'bbb');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'bbb', 'ccc');
INSERT INTO FRIEND VALUES (FRIEND_SEQ.NEXTVAL, 'bbb', 'aaa');

SELECT * FROM FRIEND;

-- 친구목록
SELECT FID, MNAME FROM FRIEND F, MEMBER M WHERE M.MID = F.FID AND F.MID = 'aaa' ORDER BY FID;

-- 친구 수
SELECT COUNT(*) FROM FRIEND WHERE MID = 'aaa';

-- 내친구 리스트에서 검색
SELECT FID, MNAME FROM FRIEND F, MEMBER M WHERE M.MID = F.FID AND F.MID = 'aaa' AND MNAME LIKE '%'||'닉네임'||'%' ORDER BY FID;

-- 친구 찾기
SELECT * FROM MEMBER WHERE MNAME LIKE '%'||''||'%';
SELECT MID, MNAME, (SELECT COUNT(*) FROM FRIEND WHERE FID = 'ccc' AND MID = MEMBER.MID) EXISTENT FROM MEMBER ORDER BY MID;
SELECT count(*) FROM FRIEND WHERE MID='aaa' and fid='iii';

-- 날 팔로우한 친구 목록
SELECT F.MID, MNAME,(SELECT COUNT(*) FROM FRIEND WHERE FID = 'ccc' AND MID = MEMBER.MID) EXISTENT  FROM FRIEND F, MEMBER M WHERE M.MID = F.FID AND F.FID = 'aaa' ORDER BY FID;

-- 친구 삭제
DELETE FROM FRIEND WHERE MID = 'aaa' AND FID = 'ccc';

DROP TABLE QNABOARD;
DROP TABLE NOTICEBOARD;
DROP SEQUENCE QNABOARD_SEQ;
DROP SEQUENCE NOTICEBOARD_SEQ;

-- 공지사항
CREATE TABLE NOTICEBOARD(
    NNO NUMBER(8) PRIMARY KEY,
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    NTITLE VARCHAR2(100) NOT NULL,
    NCONTENT VARCHAR2(3000) NOT NULL,
    NRDATE DATE DEFAULT SYSDATE,
    NHIT NUMBER(8) DEFAULT 0,
    NIP VARCHAR2(20)
);

CREATE SEQUENCE NOTICEBOARD_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

-- 공지사항 등록
INSERT INTO NOTICEBOARD (NNO, AID, NTITLE, NCONTENT, NIP)
    VALUES (NOTICEBOARD_SEQ.NEXTVAL, 'admin', '공지', '공지합니다', '127.0.0.1');
    
select * from admin;
insert into admin values ('admin', '111', 0);
commit;
-- 공지사항 목록
SELECT *
    FROM (SELECT ROWNUM RN, A.*
            FROM (SELECT * FROM NOTICEBOARD ORDER BY NNO DESC) A)
    WHERE RN BETWEEN 1 AND 10;

-- 공지사항 수정
UPDATE NOTICEBOARD SET NTITLE = '수정공지', NCONTENT = '수정공지합니다', NIP = '127.0.0.2'
    WHERE NNO = 1;

-- 공지사항 삭제
DELETE FROM NOTICEBOARD WHERE NNO = 2;

-- 공지사항 조회수 증가
UPDATE NOTICEBOARD SET NHIT = NHIT + 1 WHERE NNO = 1;

-- 공지사항 갯수
SELECT COUNT(*) FROM NOTICEBOARD;

-- 공지사항 MODEL 가져오기 / CONTENT
SELECT * FROM NOTICEBOARD WHERE NNO = 1;

-- QNA
CREATE TABLE QNABOARD(
    QNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    AID VARCHAR2(15) REFERENCES ADMIN(AID),
    QWRITER VARCHAR2(30) NOT NULL,
    QTITLE VARCHAR2(100) NOT NULL,
    QCONTENT VARCHAR2(3000) NOT NULL,
    QRDATE DATE DEFAULT SYSDATE,
    QHIT NUMBER(8) DEFAULT 0,
    QGROUP NUMBER(8),
    QSTEP NUMBER(4),
    QINDENT NUMBER(4),
    QIP VARCHAR2(20)
);

CREATE SEQUENCE QNABOARD_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

-- QNA 등록
INSERT INTO QNABOARD (QNO, MID, QWRITER, QTITLE, QCONTENT, QGROUP, QSTEP, QINDENT, QIP)
    VALUES (QNABOARD_SEQ.NEXTVAL, 'aaa', '최강','문의드립니다', '답변주세요', QNABOARD_SEQ.CURRVAL, 0, 0, '127.0.0.1');

-- QNA 수정
UPDATE QNABOARD SET QTITLE = '수정문의드립니다', QCONTENT = '수정답변주세요' WHERE QNO = 1;

-- QNA 삭제
DELETE FROM QNABOARD WHERE QNO = 2;

-- QNA 가져오기 / QNA CONTENT
SELECT * FROM QNABOARD WHERE QNO = 1;

-- QNA 조회수 증가
UPDATE QNABOARD SET QHIT = QHIT + 1 WHERE QNO = 1;

-- QNA 리스트
SELECT *
    FROM (SELECT ROWNUM RN, A.*
            FROM (SELECT * FROM QNABOARD
                     ORDER BY QGROUP DESC, QSTEP) A)
    WHERE RN BETWEEN 1 AND 10;

-- MY QNA 리스트
SELECT *
    FROM (SELECT ROWNUM RN, A.*
            FROM (SELECT * FROM QNABOARD
                     ORDER BY QGROUP DESC, QSTEP) A)
    WHERE MID = 'qqq' AND RN BETWEEN 1 AND 10;

-- 답글 전 STEP
UPDATE QNABOARD SET QSTEP = QSTEP + 1 WHERE QGROUP = 1 AND QSTEP > 0;

-- 답글
INSERT INTO QNABOARD (QNO, MID, AID, QWRITER,QTITLE, QCONTENT, QGROUP, QSTEP, QINDENT, QIP)
    VALUES (QNABOARD_SEQ.NEXTVAL, 'qqq', 'admin', '관리자', '답변드립니다', '이해하셨죠?', 1, 1, 1, '127.0.0.1');

-- MY QNA 개수
SELECT COUNT(*) FROM QNABOARD WHERE MID = 'qqq';

COMMIT;



DROP TABLE ALERT;
DROP TABLE ALERT_CODE;
DROP SEQUENCE ALERT_SEQ;
DROP SEQUENCE ALERT_CODE_SEQ;

CREATE TABLE ALERT_CODE(
    ALCODE NUMBER(8) PRIMARY KEY,
    CODENAME VARCHAR2(30)
);

CREATE TABLE ALERT(
    ALNO NUMBER(8) PRIMARY KEY,
    MID VARCHAR2(15) REFERENCES MEMBER(MID),
    FID VARCHAR2(15) REFERENCES MEMBER(MID),
    ALCODE NUMBER(8) REFERENCES ALERT_CODE(ALCODE),
    ALCHECK NUMBER(1) DEFAULT 0,
    ALDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE ALERT_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE ALERT_CODE_SEQ
    MAXVALUE 99999999
    NOCACHE
    NOCYCLE;

INSERT INTO ALERT_CODE VALUES (ALERT_CODE_SEQ.NEXTVAL, '팔로우');
INSERT INTO ALERT_CODE VALUES (ALERT_CODE_SEQ.NEXTVAL, '언팔로우');
commit;
INSERT INTO ALERT (ALNO, MID, FID, ALCODE) VALUES (ALERT_SEQ.NEXTVAL, 'aaa', 'eee', 1);
INSERT INTO ALERT (ALNO, MID, FID, ALCODE) VALUES (ALERT_SEQ.NEXTVAL, 'eee', 'aaa', 2);
INSERT INTO ALERT (ALNO, MID, FID, ALCODE) VALUES (ALERT_SEQ.NEXTVAL, 'aaa', 'fff', 1);
INSERT INTO ALERT (ALNO, MID, FID, ALCODE) VALUES (ALERT_SEQ.NEXTVAL, 'aaa', 'ppp', 1);
INSERT INTO ALERT (ALNO, MID, FID, ALCODE) VALUES (ALERT_SEQ.NEXTVAL, 'aaa', 'rrr', 1);

delete from alert where alno = 20;

SELECT AL.*, CODENAME FROM ALERT AL, ALERT_CODE AC WHERE AL.ALCODE = AC.ALCODE AND (MID = 'aaa' OR FID = 'aaa') ORDER BY ALDATE DESC, ALCHECK;

UPDATE ALERT SET ALCHECK = 1 WHERE ALNO = 2 AND ALCHECK = 0;

SELECT COUNT(*) FROM (SELECT * FROM ALERT WHERE (MID = 'aaa' OR FID = 'aaa') AND ALCHECK = 0);

SELECT * 
    FROM (SELECT ROWNUM RN, A.* 
            FROM (SELECT AL.*, CODENAME, M1.MNAME MIDNAME, M2.MNAME FIDNAME
                    FROM ALERT AL, ALERT_CODE AC, MEMBER M1, MEMBER M2
                    WHERE M1.MID = AL.MID AND AL.FID = M2.MID AND AL.ALCODE = AC.ALCODE AND (AL.MID = 'aaa' OR AL.FID = 'aaa')
                    ORDER BY ALDATE DESC) A)
    WHERE RN BETWEEN 1 AND 10;

SELECT * FROM MEMBER;

UPDATE ALERT SET ALCHECK = 0;
rollback;
cOMMIT;

select * from friend;
delete from friend where fno = 9;
