--회원 더미
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL)
    VALUES('aaa', '1', '홍길동', '1999-09-09', 'aaa@naver.com');
INSERT INTO MEMBER (MID, MPW, MNAME, MBIRTH, MEMAIL)
    VALUES('bbb', '1', '김길동', '1999-09-10', 'bbb@naver.com');

-- 투두 
INSERT INTO TODO VALUES(TODO_SEQ.NEXTVAL, 'aaa', '국어 노트 정리하기', '0', '2022-07-28');
INSERT INTO TODO VALUES(TODO_SEQ.NEXTVAL, 'aaa', '수학 노트 정리하기', '0', '2022-07-28');

-- 일기
INSERT INTO 
    DIARYBOARD(DNUM, DTITLE, MID, TNO, DCONTENT, DHIT, DSTATUS, DRDATE, DIP)
    VALUES(DIARYBOARD_SEQ.NEXTVAL, '오늘의 반성일기', 'aaa', NULL, '오늘은 아무것도 하지 못했어요ㅠㅠ', 0, 2, '2022-07-28', '127.00.00.01');
INSERT INTO 
    DIARYBOARD(DNUM, DTITLE, MID, TNO, DCONTENT, DHIT, DSTATUS, DRDATE, DIP)
    VALUES(DIARYBOARD_SEQ.NEXTVAL, '오늘의 반성일기', 'bbb', NULL, '오늘은 아무것도 하지 못했어요ㅠㅠ', 0, 2, '2022-07-28', '127.00.00.01');
INSERT INTO 
    DIARYBOARD(DNUM, DTITLE, MID, TNO, DCONTENT, DHIT, DSTATUS, DRDATE, DIP)
    VALUES(DIARYBOARD_SEQ.NEXTVAL, '오늘의 반성일기', 'bbb', NULL, '오늘은 아무것도 하지 못했어요ㅠㅠ', 0, 1, '2022-07-28', '127.00.00.01');
    
COMMIT;
