--관리자
--관리자 등록
INSERT INTO ADMIN (aID, aPW, aGRADE) VALUES ('d111', '111', 1);

--관리자 목록
SELECT * FROM ADMIN;

--관리자 삭제
DELETE FROM ADMIN WHERE AID='MMM';


--감상문
--감상문 추가
INSERT INTO RBOARD (RNUM,MID,RTITLE,RCONTENT, RFILENAME, RRDATE,RSTATUS, RIP) 
            VALUES(RSEQ.NEXTVAL, 'aaa', '테스트보드','테스트보드입니다', NULL, SYSDATE, 0,'124.01.01');
--수정

UPDATE RBOARD SET RTITLE = '테스트1',
            RCONTENT='테스트1입니다', 
            RFILENAME = NULL,
            RSTATUS= 1
            WHERE RNUM=2;

            
--삭제(할때 해시태그도 삭제되어야함)
DELETE RBOARD WHERE RNUM =0;
 

--출력

--내가 쓴 감상문 리스트(댓글 출력, 검색 가능)
SELECT *
    FROM(SELECT ROWNUM RN, A.* 
        FROM(SELECT R.*, MNAME,(SELECT COUNT(*)FROM RPBOARD B WHERE B.RNUM= R.RNUM)AS CNT FROM RBOARD R, MEMBER M 
            WHERE M.MID = R.MID and r.mid='aaa' AND RTITLE LIKE '%'||''||'%' ORDER BY RRDATE DESC, R.RNUM DESC)A)
        WHERE RN BETWEEN 1 AND 30;
            
--내가 쓴 감상문 갯수
SELECT COUNT(*)RCNT 
    FROM(SELECT ROWNUM RN, A.*
				FROM(SELECT R.*, MNAME,(SELECT COUNT(*)FROM RPBOARD B WHERE B.RNUM= R.RNUM)AS
				CNT FROM RBOARD R, MEMBER M WHERE M.MID = R.MID and r.mid='aaa' AND RTITLE LIKE
				'%'||''||'%' ORDER BY RRDATE DESC)A);
                
--내가 볼 수 있는 감상문 (검색 안한 경우)
SELECT A.* 
    FROM(SELECT ROWNUM RN, R.*, MNAME, (SELECT COUNT(*)FROM RPBOARD B WHERE B.RNUM= R.RNUM)AS RCNT FROM RBOARD R, MEMBER M, FRIEND F
                WHERE((M.MID = R.MID AND F.MID = R.MID AND MSTATUS =1 AND RSTATUS=0) 
                 OR (M.MID=F.FID AND MSTATUS =1 AND RSTATUS = 1 AND F.MID='aaa')
                  OR (M.MID=R.MID AND F.MID=R.MID AND R.MID='aaa' AND RSTATUS =2 ))ORDER BY RRDATE DESC )A
			WHERE RN BETWEEN 1 AND 50;
            
       
--내가 볼 수 있는 감상문(제목 검색한 경우)

SELECT A.* 
    FROM(SELECT ROWNUM RN, r.*, MNAME, (SELECT COUNT(*)FROM RPBOARD B WHERE B.RNUM= R.RNUM)AS RCNT FROM RBOARD R, MEMBER M, FRIEND F
                WHERE(M.MID = R.MID AND F.MID = M.MID AND MSTATUS =1 AND RSTATUS=0 AND RTITLE LIKE '%'||'보드'||'%') 
                 OR (M.MID=F.FID AND R.MID=F.FID AND MSTATUS =1 AND RSTATUS = 1 AND F.MID='aaa' AND RTITLE LIKE '%'||'보드'||'%')
                  OR (M.MID=R.MID AND F.MID=R.MID AND R.MID='aaa' AND RSTATUS =2 AND RTITLE LIKE '%'||'보드'||'%') ORDER BY RRDATE DESC)A
        WHERE RN BETWEEN 1 AND 50;
        
--내가 볼 수 있는 감상문 개수 (검색 안 했을 때)

SELECT COUNT(*)CNT FROM RBOARD R, MEMBER M, FRIEND F 
    WHERE (M.MID = R.MID AND F.MID = R.MID AND MSTATUS =1 AND RSTATUS=0) 
           OR (M.MID=F.FID AND R.MID=F.FID AND MSTATUS =1 AND RSTATUS = 1 AND F.MID='aaa')
            OR (M.MID=R.MID AND F.MID=R.MID AND R.MID='aaa' AND RSTATUS =2 );

--타이틀 검색했을 때
SELECT COUNT(*)CNT FROM RBOARD R, MEMBER M, FRIEND F 
    WHERE (M.MID = R.MID AND F.MID = R.MID AND MSTATUS =1 AND RSTATUS=0 AND  RTITLE LIKE '%'||'보드'||'%') 
        OR (M.MID=F.FID AND R.MID=F.FID AND MSTATUS =1 AND RSTATUS = 1 AND F.MID='aaa' AND  RTITLE LIKE '%'||'보드'||'%') 
        OR (M.MID=R.MID AND F.MID=R.MID AND R.MID='aaa' AND RSTATUS =2 AND  RTITLE LIKE '%'||'보드'||'%');   