INSERT INTO MEMBER(MID, MPW, MNAME, MBIRTH,MEMAIL,MMOTTO,MSTATUS  ) 
VALUES ('aaa', '111', '이토끼토끼', '89-01-01', 'bunny0101@naver.com', '살다보면 좋은 일이 생긴다', 1);

commit;
select * from rboard;
--게시판
INSERT INTO RBOARD (RNUM,MID,RTITLE,RCONTENT, RFILENAME, RRDATE,RSTATUS, RIP) 
            VALUES(RSEQ.NEXTVAL, 'AAA', '테스트보드7','테스트보드입니다', NULL, SYSDATE, 1,'124.01.01');
INSERT INTO RBOARD (RNUM,MID,RTITLE,RCONTENT, RFILENAME, RRDATE,RSTATUS, RIP) 
            VALUES(RSEQ.NEXTVAL, 'AAA', '테스트8','테스트보드입니다', NULL, SYSDATE, 1,'124.01.01');
INSERT INTO RBOARD (RNUM,MID,RTITLE,RCONTENT, RFILENAME, RRDATE,RSTATUS, RIP) 
            VALUES(RSEQ.NEXTVAL, 'AAA', '테스트9','테스트보드입니다', NULL, SYSDATE, 2,'124.01.01');
INSERT INTO RBOARD (RNUM,MID,RTITLE,RCONTENT, RFILENAME, RRDATE,RSTATUS, RIP) 
            VALUES(RSEQ.NEXTVAL, 'AAA', '테스트10','테스트보드입니다', NULL, SYSDATE, 2,'124.01.01');
INSERT INTO RBOARD (RNUM,MID,RTITLE,RCONTENT, RFILENAME, RRDATE,RSTATUS, RIP) 
            VALUES(RSEQ.NEXTVAL, 'AAA', '테스트5','테스트보드입니다', NULL, SYSDATE, 0,'124.01.01');
            
INSERT INTO RBOARD (RNUM,MID,RTITLE,RCONTENT, RFILENAME, RRDATE,RSTATUS, RIP) 
            VALUES(RSEQ.NEXTVAL, 'aaa', '테스트6','테스트보드입니다', NULL, SYSDATE, 0,'124.01.01');
   select * from member;         
--댓글
    INSERT INTO RPBOARD (RPNUM,RNUM,MID,RPCONTENT,RPDATE,RPGROUP, RPINDENT, RPIP)
    VALUES (RPSEQ.NEXTVAL, 1, 'AAA', '댓글입니다', SYSDATE, RPSEQ.CURRVAL, 0,'127.10.10');
      INSERT INTO RPBOARD (RPNUM,RNUM,MID,RPCONTENT,RPDATE,RPGROUP, RPINDENT, RPMENTION, RPIP)
    VALUES (RPSEQ.NEXTVAL, 1, 'aaa', '댓글입니다', SYSDATE, 1, 1,'이토끼토끼','127.10.10');
     INSERT INTO RPBOARD (RPNUM,RNUM,MID,RPCONTENT,RPDATE,RPGROUP, RPINDENT, RPMENTION, RPIP)
    VALUES (RPSEQ.NEXTVAL, 1, 'aaa', '댓글입니다2', SYSDATE, 1, 1,'이토끼토끼','127.10.10');
